### ISSUE TITLE
Code organization

### ISSUE THREAD

**Issue by conartist6** [therootcompany/walk.js#3]
I'm really scratching my head over this. One module modifies the exports of the other, while also copying all of its code? I had put a usage of this up in a PR, but on second thought I think I'll write my own.

**Comment by coolaj86** [comment]
Could you give an example of what you're talking about?

This is a single file, no dependencies, and therefore doesn't modify any other exports.
https://github.com/therootcompany/walk.js/blob/master/walk.js

Are you opening the issue in the right place? Or is there another walk module with a similar name that you're confused about?

**Comment by conartist6** [comment]
Perhaps [create.js](https://github.com/therootcompany/walk.js/blob/master/create.js) was not meant to be included then?

**Comment by coolaj86** [comment]
Oh, the original walk didn't have a way to pass in options so rather than break the API I copied it to a version that accepts options that modify the state of the walker.

But what's your point?

You don't like this?

```js
require('./parent').child = require('./child');
```

Meh, go write your own then I guess.

**Comment by conartist6** [comment]
Uh, my point was that instead of copying the less flexible version to create the more flexible version you should **use** the more flexible version to create the less flexible version.

**Comment by coolaj86** [comment]
Except that first and foremost I shouldn't break the existing API.

And this is pretty much the most lightweight and fastest implementation of `walk` in the ecosystem, so I'd rather copy a little than put in extra checks that aren't actually needed half the time.

**Comment by conartist6** [comment]
Well that depends on your interpretation of the semver spec. But since presumably your users have come to depend on the implementation you have, it would be courteous to make such a change a new major version.

**Comment by conartist6** [comment]
Wait, I thought you were talking about the relative paths for a second. I don't see why you'd be breaking an existing API... Do you have any perf data to back up the usefulness of the optimization? DRY is one of those things I don't give up without a very good reason.

**Comment by coolaj86** [comment]
> I thought you were talking about the relative paths for a second

That's the other issue.

> I don't see why you'd be breaking an existing API

```js
var Walk = require('walk').Walk;
Walk.walk(limitedOptions);
```

You change the require, you change the API.

> DRY is one of those things I don't give up without a very good reason.

- https://creedsofcraftsmanship.com
- https://kentcdodds.com/blog/aha-programming
- https://go-proverbs.github.io/
- https://github.com/ewjoachim/zen-of-python

> Do you have any perf data to back up the usefulness of the optimization?

No, and I'm not a performance maximalist. I am a clean code maximalist and the simpler version of the code is easier to reason about.

If I were a performance maximalist I could easily show how a microbenchmark can be manipulated to show the increased performance... but the itsy bit of extra performance is really just in the noise and wasn't my primary point.

**Comment by coolaj86** [comment]
Just look at it: https://github.com/therootcompany/walk.js/blob/master/walk.js

Less than 35 lines (11-45 + comments). Very low complexity.

It's the Mary Poppins of walk functions.

**Comment by conartist6** [comment]
OK I'll grant you that, but functions that are young and beautiful do not always stay so.
